---
- hosts: all
  become: yes
  tasks:
          - name: creating primary partition
            parted:
                    device: /dev/sdb
                    number: 1
                    part_end: 800MiB
                    state: present
            register: partition

          - name: debug output
            debug:
                    var: partition

          - name: creating volume group
            lvg:
                    vg: vg_database
                    pvs: /dev/sdb1
                    state: present
            register: vgs    

          - name: debug vgs
            debug:
                    var: vgs

          - name: creating logical volume
            lvol:
                    vg: vg_database
                    lv: lv_mysql
                    size: 512M
                    state: present
            register: lvs

          - name: debug lvs
            debug:
                    var: lvs
                    
          - name: xfs filesystem assign
            filesystem:
                    fstype: xfs
                    dev: /dev/vg_database/lv_mysql
            register: filesystem

          - name: debug filesystem
            debug:
                    var: filesystem 

          - name: mounting permanently
            mount:
                    path: /mnt/mysql_backups
                    src: /dev/vg_database/lv_mysql
                    fstype: xfs
                    state: mounted
            register: mounts

          - name: debug mounts
            debug:
                    var: mounts  









