---
 - name: implement nfs server
   hosts: nfsserver
   tasks:
    
    - name: install software
      dnf:
        name: nfs-utils
        state: present

    - name: start and enable service
      service:
        name: nfs-server
        state: started
        enabled: yes

    - name: create share
      file:
        path: /share1
        state: directory

    - name: edit configuration
      lineinfile:
        path: /etc/exports
        line: '/share1 3.6.38.7(ro)'
        state: present

    - name: update the share
      shell:
        cmd: exportfs -r 
...
